/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas;

import AccesoADatos.AfiliadoData;
import AccesoADatos.OrdenData;
import AccesoADatos.PrestadorData;
import Principal.Afiliado;
import Principal.Orden;
import Principal.Prestador;
import java.sql.Date;
import java.time.LocalDate;
import java.time.ZoneId;
import java.util.List;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author iarak
 */
public class Ordenes extends javax.swing.JInternalFrame {

    private DefaultTableModel modelotabla = new DefaultTableModel();
    AfiliadoData ad = new AfiliadoData();
    PrestadorData pd = new PrestadorData();
    OrdenData od = new OrdenData();
    private int seleccionarFila;
    private int valorDNIa;
    private int valorDNIp;
    private LocalDate valorFecha;
    Orden orden = new Orden();

    /**
     * Creates new form Ordenes
     */
    public Ordenes() {
        initComponents();
        cargarComboAfiliado();
        cargarComboPrestador();
        armarCabecera();
        cargarTabla();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JCBprestadores = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        JBagregarOrden = new javax.swing.JButton();
        JBeliminar = new javax.swing.JButton();
        JBmodificar = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        JCBformaPago = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        JTimporte = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        JDCfecha = new com.toedter.calendar.JDateChooser();
        JCBafiliados = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        JTordenes = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        JCBprestadores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JCBprestadoresActionPerformed(evt);
            }
        });
        getContentPane().add(JCBprestadores, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 110, 330, -1));

        jLabel4.setText("Afiliado");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 190, -1, -1));

        jLabel5.setText("Fecha de orden");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 280, -1, -1));

        JBagregarOrden.setText("Agregar Orden");
        JBagregarOrden.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBagregarOrdenActionPerformed(evt);
            }
        });
        getContentPane().add(JBagregarOrden, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 510, -1, -1));

        JBeliminar.setText("Eliminar Orden");
        JBeliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBeliminarActionPerformed(evt);
            }
        });
        getContentPane().add(JBeliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 630, -1, -1));

        JBmodificar.setText("Modificar Orden");
        getContentPane().add(JBmodificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 570, -1, -1));

        jLabel7.setText("Forma de Pago");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 440, 150, 30));

        JCBformaPago.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "", "Efectivo", "Transferencia", "Tarjeta" }));
        JCBformaPago.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JCBformaPagoActionPerformed(evt);
            }
        });
        getContentPane().add(JCBformaPago, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 440, 330, -1));

        jLabel6.setText("Importe");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 360, -1, -1));

        JTimporte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTimporteActionPerformed(evt);
            }
        });
        getContentPane().add(JTimporte, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 360, 330, -1));

        jLabel2.setText("Prestador");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 110, -1, -1));
        getContentPane().add(JDCfecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 280, 330, 30));

        getContentPane().add(JCBafiliados, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 190, 330, -1));

        JTordenes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        JTordenes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JTordenesMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(JTordenes);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 110, -1, 480));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel3.setText("Órdenes");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 10, 140, 50));

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(458, 264, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\iarak\\OneDrive\\Imágenes\\massalud.png")); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, -30, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JCBprestadoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JCBprestadoresActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JCBprestadoresActionPerformed

    private void JTimporteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTimporteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JTimporteActionPerformed

    private void JBagregarOrdenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBagregarOrdenActionPerformed
        // TODO add your handling code here:
        LocalDate fecha = null;
        if (JDCfecha.getDate() != null) {
            fecha = JDCfecha.getDate().toInstant().atZone(ZoneId.systemDefault()).toLocalDate();
        }
        Afiliado afiliado = (Afiliado) JCBafiliados.getSelectedItem();
        Prestador prestador = (Prestador) JCBprestadores.getSelectedItem();

        Orden orden = new Orden(fecha, (String) JCBformaPago.getSelectedItem(), Double.parseDouble(JTimporte.getText()), afiliado.getDNI(), prestador.getDNI());
        od.añadirOrden(orden);
    }//GEN-LAST:event_JBagregarOrdenActionPerformed

    private void JBeliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBeliminarActionPerformed
        // TODO add your handling code here:
        od.eliminarOrden(valorDNIa, valorFecha, valorDNIp);
    }//GEN-LAST:event_JBeliminarActionPerformed

    private void JTordenesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JTordenesMouseClicked
        // TODO add your handling code here:
        seleccionarFila = JTordenes.rowAtPoint(evt.getPoint());
        valorDNIa = (int) JTordenes.getValueAt(seleccionarFila, 3);
        valorDNIp = (int) JTordenes.getValueAt(seleccionarFila, 4);
        valorFecha = (LocalDate) JTordenes.getValueAt(seleccionarFila, 0);
        System.out.println(valorDNIa +" "+ valorDNIp +" "+ valorFecha);
        
        
    }//GEN-LAST:event_JTordenesMouseClicked

    private void JCBformaPagoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JCBformaPagoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JCBformaPagoActionPerformed

    private void armarCabecera() {
        modelotabla.addColumn("Fecha");
        modelotabla.addColumn("Pago");
        modelotabla.addColumn("Importe");
        modelotabla.addColumn("DNI afiliado");
        modelotabla.addColumn("DNI prestador");
        JTordenes.setModel(modelotabla);
    }

    private void cargarComboAfiliado() {
        JCBafiliados.removeAllItems();
        Afiliado a = new Afiliado();
        JCBafiliados.addItem(a);
        for (Afiliado afiliado : ad.listarAfiliados()) {
            JCBafiliados.addItem(afiliado);
        }
    }

    private void cargarComboPrestador() {
        JCBprestadores.removeAllItems();
        Prestador p = new Prestador();
        JCBprestadores.addItem(p);
        for (Prestador prestador : pd.listarPrestadores()) {
            JCBprestadores.addItem(prestador);
        }
    }

    private void borrarFilas() {
        ((DefaultTableModel) JTordenes.getModel()).setRowCount(0);

    }

    private void cargarTabla() {
        borrarFilas();

        List<Orden> listarEspecialidades = od.listarOrdenes();
        for (Orden ord : listarEspecialidades) {
            modelotabla.addRow(new Object[]{ord.getFecha(),ord.getFormaDePago(),ord.getImporte(),ord.getDNIafiliado(), ord.getDNIprestador()});
        }
    }
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JBagregarOrden;
    private javax.swing.JButton JBeliminar;
    private javax.swing.JButton JBmodificar;
    private javax.swing.JComboBox<Afiliado> JCBafiliados;
    private javax.swing.JComboBox<String> JCBformaPago;
    private javax.swing.JComboBox<Prestador> JCBprestadores;
    private com.toedter.calendar.JDateChooser JDCfecha;
    private javax.swing.JTextField JTimporte;
    private javax.swing.JTable JTordenes;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
