/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas;

import AccesoADatos.EspecialidadData;
import AccesoADatos.PrestadorData;
import Principal.Especialidad;
import Principal.Prestador;

/**
 *
 * @author iarak
 */
public class Prestadores extends javax.swing.JInternalFrame {
    PrestadorData pd = new PrestadorData();
    EspecialidadData ed = new EspecialidadData();
    public Prestadores() {
        initComponents();
        cargarCombo();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        JTnombre = new javax.swing.JTextField();
        JTapellido = new javax.swing.JTextField();
        JTdni = new javax.swing.JTextField();
        JTdomicilio = new javax.swing.JTextField();
        JTtelefono = new javax.swing.JTextField();
        JRBactivo = new javax.swing.JRadioButton();
        JBagregarPrestador = new javax.swing.JButton();
        JBmodificarPrestador = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        JLnombre = new javax.swing.JLabel();
        JLapellido = new javax.swing.JLabel();
        JLdni = new javax.swing.JLabel();
        JLdomicilio = new javax.swing.JLabel();
        JLtelefono = new javax.swing.JLabel();
        JLtextoAdv = new javax.swing.JLabel();
        JBrellenarCampos = new javax.swing.JButton();
        JCBprestadores = new javax.swing.JComboBox<>();
        JLespecialidad = new javax.swing.JLabel();
        JCBespecialidad = new javax.swing.JComboBox<>();
        JBsalir = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setMaximumSize(new java.awt.Dimension(1025, 739));
        setMinimumSize(new java.awt.Dimension(1025, 739));
        setPreferredSize(new java.awt.Dimension(1025, 739));

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel5.setText("DNI:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 320, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel4.setText("Apellido:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 280, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel3.setText("Nombre:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 240, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel2.setText("Prestadores");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 30, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel6.setText("Domicilio:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 360, -1, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel7.setText("Especialidad:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 400, -1, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel8.setText("Telefono:");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 440, -1, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel9.setText("Activo:");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 480, -1, -1));
        jPanel1.add(JTnombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 240, 160, -1));
        jPanel1.add(JTapellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 280, 160, -1));
        jPanel1.add(JTdni, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 320, 160, -1));
        jPanel1.add(JTdomicilio, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 360, 160, -1));
        jPanel1.add(JTtelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 440, 160, -1));
        jPanel1.add(JRBactivo, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 480, -1, -1));

        JBagregarPrestador.setBackground(new java.awt.Color(0, 153, 0));
        JBagregarPrestador.setText("Agregar Prestador");
        JBagregarPrestador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBagregarPrestadorActionPerformed(evt);
            }
        });
        jPanel1.add(JBagregarPrestador, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 240, -1, 70));

        JBmodificarPrestador.setBackground(new java.awt.Color(0, 153, 0));
        JBmodificarPrestador.setText("Modificar Prestador");
        jPanel1.add(JBmodificarPrestador, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 370, -1, 70));

        jButton3.setIcon(new javax.swing.ImageIcon("C:\\Users\\iarak\\OneDrive\\Imágenes\\ayuda.png")); // NOI18N
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 531, 140, 130));

        jLabel10.setBackground(new java.awt.Color(0, 153, 0));
        jLabel10.setIcon(new javax.swing.ImageIcon("C:\\Users\\iarak\\OneDrive\\Imágenes\\prestadorImage.png")); // NOI18N
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 120, 140, 150));

        JLnombre.setText("Nombre");
        jPanel1.add(JLnombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 280, 80, -1));

        JLapellido.setText("Apellido");
        jPanel1.add(JLapellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 320, 90, -1));

        JLdni.setText("DNI");
        jPanel1.add(JLdni, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 360, 50, -1));

        JLdomicilio.setText("Domicilio");
        jPanel1.add(JLdomicilio, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 390, 90, -1));

        JLtelefono.setText("Telefono");
        jPanel1.add(JLtelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 430, 90, -1));

        JLtextoAdv.setText("No existe el prestador");
        jPanel1.add(JLtextoAdv, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 500, -1, -1));

        JBrellenarCampos.setBackground(new java.awt.Color(0, 153, 0));
        JBrellenarCampos.setText("Rellenar Campos");
        JBrellenarCampos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBrellenarCamposActionPerformed(evt);
            }
        });
        jPanel1.add(JBrellenarCampos, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 530, 240, 50));

        JCBprestadores.setBackground(new java.awt.Color(0, 153, 0));
        JCBprestadores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JCBprestadoresActionPerformed(evt);
            }
        });
        jPanel1.add(JCBprestadores, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 590, 240, -1));

        JLespecialidad.setText("Especialidad");
        jPanel1.add(JLespecialidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 460, -1, -1));

        JCBespecialidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JCBespecialidadActionPerformed(evt);
            }
        });
        jPanel1.add(JCBespecialidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 400, 200, -1));

        JBsalir.setBackground(new java.awt.Color(255, 51, 51));
        JBsalir.setForeground(new java.awt.Color(255, 255, 255));
        JBsalir.setText("Salir");
        JBsalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBsalirActionPerformed(evt);
            }
        });
        jPanel1.add(JBsalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 10, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\iarak\\OneDrive\\Imágenes\\massalud.png")); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1010, 690));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JBrellenarCamposActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBrellenarCamposActionPerformed
        // TODO add your handling code here
        Prestador prestador = pd.listarPrestadorPorDNI(Integer.parseInt(JLdni.getText()));
        Especialidad esp = new Especialidad();
        JTnombre.setText(prestador.getNombre());
        JTapellido.setText(prestador.getApellido());
        JTdni.setText(String.valueOf(prestador.getDNI()));
        JTdomicilio.setText(prestador.getDomicilio());
        JTtelefono.setText(String.valueOf(prestador.getTelefono()));
        JRBactivo.setSelected(prestador.isEstado());
        JLespecialidad.setText(ed.especialidadPorNombre(prestador.getIdEspecialidad()).toString());
        JBmodificarPrestador.setEnabled(true);
        JBagregarPrestador.setEnabled(false);
    }//GEN-LAST:event_JBrellenarCamposActionPerformed

    private void JCBprestadoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JCBprestadoresActionPerformed
        // TODO add your handling code here:

        Prestador prestador = (Prestador) JCBprestadores.getSelectedItem();
        JLnombre.setText(prestador.getNombre());
        JLapellido.setText(prestador.getApellido());
        JLdni.setText(String.valueOf(prestador.getDNI()));
        JLdomicilio.setText(prestador.getDomicilio());
        JLtelefono.setText(String.valueOf(prestador.getTelefono()));
        JLtextoAdv.setVisible(false);
        JBrellenarCampos.setEnabled(true);
    }//GEN-LAST:event_JCBprestadoresActionPerformed

    private void JBsalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBsalirActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        dispose();
    }//GEN-LAST:event_JBsalirActionPerformed

    private void JBagregarPrestadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBagregarPrestadorActionPerformed
        // TODO add your handling code here:
        Especialidad especialidad = (Especialidad) JCBespecialidad.getSelectedItem();
        Prestador prestador = new Prestador(JTnombre.getText(), JTapellido.getText(),Integer.parseInt(JTdni.getText()),JRBactivo.isEnabled(),ed.especialidadPorId(especialidad.getTipo()), Integer.parseInt(JTtelefono.getText()), JTdomicilio.getText());
        pd.añadirPrestador(prestador);
    }//GEN-LAST:event_JBagregarPrestadorActionPerformed

    private void JCBespecialidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JCBespecialidadActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_JCBespecialidadActionPerformed
    
    private void cargarCombo (){
        for (Especialidad especialidad : ed.listarEspecialidades()) {
            JCBespecialidad.addItem(especialidad);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JBagregarPrestador;
    private javax.swing.JButton JBmodificarPrestador;
    private javax.swing.JButton JBrellenarCampos;
    private javax.swing.JButton JBsalir;
    private javax.swing.JComboBox<Especialidad> JCBespecialidad;
    private javax.swing.JComboBox<Prestador> JCBprestadores;
    private javax.swing.JLabel JLapellido;
    private javax.swing.JLabel JLdni;
    private javax.swing.JLabel JLdomicilio;
    private javax.swing.JLabel JLespecialidad;
    private javax.swing.JLabel JLnombre;
    private javax.swing.JLabel JLtelefono;
    private javax.swing.JLabel JLtextoAdv;
    private javax.swing.JRadioButton JRBactivo;
    private javax.swing.JTextField JTapellido;
    private javax.swing.JTextField JTdni;
    private javax.swing.JTextField JTdomicilio;
    private javax.swing.JTextField JTnombre;
    private javax.swing.JTextField JTtelefono;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
